package com.etaw.cleaner

object WebsiteTable {
    val MAP: Map<String, String> = mapOf(
        "com.tencent.mm" to "https://weixin.qq.com",
        "com.tencent.mobileqq" to "https://im.qq.com",
        "com.eg.android.AlipayGphone" to "https://www.alipay.com",
        "com.taobao.taobao" to "https://www.taobao.com",
        "com.jingdong.app.mall" to "https://www.jd.com",
        "tv.danmaku.bili" to "https://www.bilibili.com",
        "com.ss.android.ugc.aweme" to "https://www.douyin.com",
        "com.sina.weibo" to "https://www.weibo.com",
        "com.zhihu.android" to "https://www.zhihu.com",
        "com.xingin.xhs" to "https://www.xiaohongshu.com",
        "com.sankuai.meituan" to "https://www.meituan.com",
        "com.dianping.v1" to "https://www.dianping.com",
        "com.tencent.wework" to "https://work.weixin.qq.com",
        "com.alibaba.android.rimet" to "https://www.dingtalk.com",
        "com.netease.cloudmusic" to "https://music.163.com",
        "com.tencent.qqmusic" to "https://y.qq.com",
        "com.kugou.android" to "https://www.kugou.com",
        "com.tencent.qqlive" to "https://v.qq.com",
        "com.qiyi.video" to "https://www.iqiyi.com",
        "com.youku.phone" to "https://www.youku.com",
        "com.MobileTicket" to "https://www.12306.cn",
        "com.baidu.searchbox" to "https://www.baidu.com",
        "com.quark.browser" to "https://www.quark.cn",
        "com.UCMobile" to "https://www.uc.cn",
        "com.tencent.android.qqdownloader" to "https://sj.qq.com",
        "com.wali.live" to "https://www.kuaishou.com",
        "com.bytedance.news" to "https://www.toutiao.com",
        "com.ss.android.article.news" to "https://www.toutiao.com",
        "com.baidu.tieba" to "https://tieba.baidu.com",
        "com.sdu.didi.psnger" to "https://www.didiglobal.com",
        "com.sf.activity" to "https://www.sf-express.com",
        "com.cainiao.wireless" to "https://www.cainiao.com",
        "com.taobao.idlefish" to "https://www.goofish.com",
        "com.xunmeng.pinduoduo" to "https://www.pinduoduo.com",
        "com.autonavi.minimap" to "https://www.amap.com",
        "com.baidu.BaiduMap" to "https://map.baidu.com",
        "com.tencent.map" to "https://map.qq.com",
        "com.android.chrome" to "https://www.google.com/chrome",
        "org.mozilla.firefox" to "https://www.mozilla.org/firefox",
        "com.tencent.qqmail" to "https://mail.qq.com",
        "com.kingsoft.moffice_pro" to "https://www.wps.cn",
        "cn.wps.moffice_eng" to "https://www.wps.cn",
        "com.instagram.android" to "https://www.instagram.com",
        "com.facebook.katana" to "https://www.facebook.com",
        "com.whatsapp" to "https://www.whatsapp.com",
        "com.zhiliaoapp.musically" to "https://www.tiktok.com",
        "com.spotify.music" to "https://www.spotify.com",
        "com.dropbox.android" to "https://www.dropbox.com",
        "com.google.android.youtube" to "https://www.youtube.com",
        "com.google.android.gm" to "https://mail.google.com",
        "com.google.android.apps.maps" to "https://maps.google.com",
        "com.github.android" to "https://github.com",
        "com.telegram.messenger" to "https://telegram.org",
        "com.tencent.mtt" to "https://www.qq.com",
        "com.tencent.news" to "https://news.qq.com",
        "com.douban.frodo" to "https://www.douban.com",
        "com.unionpay" to "https://www.95516.com",
        "com.cmbchina.ccd.pluto.cmbActivity" to "https://www.cmbchina.com",
        "com.android.bankabc" to "https://www.abchina.com",
        "com.icbc" to "https://www.icbc.com.cn",
        "com.ccb.longji" to "https://www.ccb.com",
        "com.jdjr.tmall.yyhd" to "https://www.taobao.com"
    )

    fun get(pkg: String): String? = MAP[pkg]
}
